E1031 - Use topics for push notifications for shared apps
staceesanti/push pull request #74
Opened 2023-12-29 17:27 UTC by IlicPavle

https://gitlab.com/vetsource/vs/-/issues/9480

2024-02-06 02:05 UTC, AlexSpear94 approved these changes

2024-04-05 10:02 UTC, anjapantovic approved these changes, later dismissed

2024-04-05 19:20 UTC, AlexSpear94 approved these changes

2025-03-24 01:04 UTC, AlexSpear94 requested changes

2025-03-24 01:04 UTC, AlexSpear94 commented on lib/client/client.js
> +    Meteor.call('raix:subscribe-to-topic', appIdentifier, topicName, stored?.token?.fcm);
```suggestion
    Meteor.call('raix:subscribe-to-topic', appIdentifier, topicName, stored.token.fcm);
```

2025-03-24 01:04 UTC, AlexSpear94 commented on lib/client/client.js
> +    Meteor.call('raix:unsubscribe-from-topic', appIdentifier, topicName, stored.token?.fcm);
```suggestion
    Meteor.call('raix:unsubscribe-from-topic', appIdentifier, topicName, stored.token.fcm);
```

2025-03-24 01:04 UTC, AlexSpear94 commented on lib/server/server.js
> +      firebaseApp.messaging().subscribeToTopic([fcmToken], `/topics/${topicName}`).then()
```suggestion
      firebaseApp.messaging().subscribeToTopic([fcmToken], `/topics/${topicName}`)
```

2025-03-24 01:04 UTC, AlexSpear94 commented on lib/server/server.js
> +      firebaseApp.messaging().unsubscribeFromTopic([fcmToken], `/topics/${topicName}`).then()
```suggestion
      firebaseApp.messaging().unsubscribeFromTopic([fcmToken], `/topics/${topicName}`)
```

2025-03-24 21:48 UTC, sortegarojas approved these changes

2025-03-26 10:41 UTC, closed without merging